onEvent('item.registry', e => {
  e.create('mass_of_wills').displayName('§6意志凝结体').tooltip('§8六种古代意志的结合物').unstackable()
  e.create('rune_of_sins').displayName('§6宗罪符文').tooltip('§8包含了七宗罪力量的符文').unstackable()
  e.create('rotten_leather').displayName('腐烂的皮革')
  e.create('uu_matter').displayName('§dUU物质')
  e.create('patrick_star').displayName('§d派大星')
  e.create('saltpeter_ingot').displayName('硝酸盐锭')
  e.create('potassium_nitrate_dust').displayName('硝酸钾粉')
  e.create('potassium_nitrate_ingot').displayName('硝酸钾锭')
  e.create('potassium_dust').displayName('钾粉')
  e.create('potassium_ingot').displayName('钾锭')
})

onEvent('block.registry', e => {
  e.create('magical_soil').displayName('§b魔法土壤').material('organic').hardness(0.6)
  e.create('nether_star_block').displayName('§e下界之星块').material('iron').hardness(2).lightLevel(1)
  e.create('saltpeter_block').displayName('硝酸盐块').material('iron')
  e.create('potassium_block').displayName('钾块').material('iron')
  e.create('potassium_nitrate_block').displayName('硝酸钾块').material('iron')
  e.create('atm_star_block').displayName('§eATM之星块').material('iron').hardness(5).lightLevel(1)
})
