# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:[push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: # optional, default is 3.x
        architecture: x64
    - name: Install yarn
      run: npm install -g yarn
    - name: install pip requirements
      run: sudo pip3 install -r requirements.txt
    - name: Run yarn 
      run: yarn ./page
